name: main workflow
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: "Hello World!!!"
        run: |
          echo "Hello World... :)"

  call-reuse-workflow-A:
    uses: ./.github/workflows/reuse-A.yml
    with:
      name: Baker Mayfield


  call-reuse-workflow-B:
    uses: ./.github/workflows/reuse-A.yml
    with:
      name: Justin Jefferson
