name: main workflow
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: "Hello World!!!"
        run: |
          echo "Hello World... :)" 

  call-reuse-workflow-A:
    uses: ./.github/workflow/reuse-A.yml
