name: main workflow
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: "Hello World!!!"
        run: |
          echo "Hello World... :)" 

  gcc:
    uses: ./.github/workflows/reusable.yml
    with:
      target-runner-labels: "['ubuntu-latest']"
      config-path: smiley/face/hehe.yml

  cuda:
    uses: ./.github/workflows/reusable.yml
    with:
      target-runner-labels: "['ubuntu-latest']"
      config-path: some/cuda/gpu.yml

