name: "Reuse workflow A"
on:
  workflow_call:
    inputs:
      name:
        required: false
        type: string
        default: "Bobby"
    outputs: {}

jobs:
  reuse-workflow-job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Say something I'm giving up on you...
        run: |
          echo "Hello there, ${{ inputs.name }}"
