name: Reusable workflow example

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string

jobs:
  gcc:
    runs-on: ubuntu-latest
    steps:
    - run: echo "${{ inputs.config-path }}"
